services:
  # Cluster store 
  store1:
    build: .
    container_name: store1
    entrypoint: ["python3", "-u", "cluster_store.py", "1"]

  store2:
    build: .
    container_name: store2
    entrypoint: ["python3", "-u", "cluster_store.py", "2"]

  store3:
    build: .
    container_name: store3
    entrypoint: ["python3", "-u", "cluster_store.py", "3"]


# Cluster sync + clientes
  node1:
    build: .
    container_name: node1
    command: ["1"]
    depends_on:
      - store1
      - store2
      - store3

  node2:
    build: .
    container_name: node2
    command: ["2"]
    depends_on:
      - store1
      - store2
      - store3

  node3:
    build: .
    container_name: node3
    command: ["3"]
    depends_on:
      - store1
      - store2
      - store3

  node4:
    build: .
    container_name: node4
    command: ["4"]
    depends_on:
      - store1
      - store2
      - store3

  node5:
    build: .
    container_name: node5
    command: ["5"]
    depends_on:
      - store1
      - store2
      - store3